# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

def abstract_pods
    pod 'ObjectMapper', '~> 1.0'
end

target 'iOSSwiftStarter' do
    abstract_pods
    pod 'Alamofire', '~> 3.0'
    pod 'AlamofireObjectMapper', '~> 2.1'
    pod 'ReactKit'
    pod 'Kugel'
    pod 'CoreStore'
    pod 'Hakuba'
    pod 'Kingfisher', '~> 1.8'
    pod 'AsyncSwift'
    pod 'StatefulViewController', '~> 1.0'
end

def testing_pods
    abstract_pods
    pod 'Quick'
    pod 'Nimble'
end

target 'iOSSwiftStarterTests' do
    testing_pods
end

target 'iOSSwiftStarterUITests' do
end
